// Catálogo integral de métodos de pago y monedas (Dólar, Sudamérica y Norteamérica)

export const CURRENCIES = [
  { code: 'USD', name: 'Dólar Estadounidense ($)', symbol: '$' },
  { code: 'PEN', name: 'Sol Peruano (S/)', symbol: 'S/' },
  { code: 'BOB', name: 'Boliviano (Bs.)', symbol: 'Bs.' },
  { code: 'COP', name: 'Peso Colombiano ($)', symbol: '$' },
  { code: 'MXN', name: 'Peso Mexicano ($)', symbol: '$' },
  { code: 'CLP', name: 'Peso Chileno ($)', symbol: '$' },
  { code: 'ARS', name: 'Peso Argentino ($)', symbol: '$' },
  { code: 'BRL', name: 'Real Brasileño (R$)', symbol: 'R$' },
  { code: 'CAD', name: 'Dólar Canadiense ($)', symbol: '$' },
  { code: 'EUR', name: 'Euro (€)', symbol: '€' },
  { code: 'OTRO', name: 'Otra moneda', symbol: '¤' },
];

export const PAYMENT_REGIONS = [
  {
    id: 'internacional',
    name: 'Dólar / Internacional',
    defaultCurrency: 'USD',
    methods: [
      {
        key: 'paypal',
        label: 'PayPal',
        currency: 'USD',
        badge: 'Global USD',
        accountLabel: 'Correo electrónico de su cuenta PayPal',
        accountPlaceholder: 'ejemplo@correo.com',
        accountType: 'email',
        requiresHolder: false,
      },
      {
        key: 'zelle_global',
        label: 'Zelle (EE.UU.)',
        currency: 'USD',
        badge: 'USD',
        accountLabel: 'Correo o teléfono registrado en Zelle',
        accountPlaceholder: 'correo@ejemplo.com o +1 555-0199',
        accountType: 'text',
        requiresHolder: true,
        holderLabel: 'Nombre del titular en Zelle',
      },
      {
        key: 'swift_usd',
        label: 'Transferencia SWIFT (USD)',
        currency: 'USD',
        badge: 'Interbancario USD',
        accountLabel: 'Número de cuenta / IBAN en USD',
        accountPlaceholder: 'Ej. 01234567890 o US123456789',
        accountType: 'text',
        requiresBankName: true,
        requiresSwift: true,
        requiresHolder: true,
        holderLabel: 'Nombre completo del titular',
      },
      {
        key: 'wise',
        label: 'Wise (TransferWise)',
        currency: 'USD',
        badge: 'USD / Multi',
        accountLabel: 'Correo registrado en Wise o número de cuenta',
        accountPlaceholder: 'ejemplo@correo.com',
        accountType: 'text',
        requiresHolder: true,
      },
      {
        key: 'payoneer',
        label: 'Payoneer',
        currency: 'USD',
        badge: 'USD',
        accountLabel: 'Correo electrónico de Payoneer',
        accountPlaceholder: 'ejemplo@correo.com',
        accountType: 'email',
        requiresHolder: false,
      },
    ],
  },
  {
    id: 'peru',
    name: 'Perú',
    defaultCurrency: 'PEN',
    currencies: ['PEN', 'USD'],
    methods: [
      {
        key: 'bcp',
        label: 'BCP (Banco de Crédito)',
        currency: 'PEN',
        badge: 'Soles / USD',
        accountLabel: 'Número de cuenta BCP',
        accountPlaceholder: 'Ej. 191-XXXXXXXX-X-XX',
        accountType: 'numeric',
        supportsCci: true,
        requiresHolder: false,
      },
      {
        key: 'yape',
        label: 'YAPE',
        currency: 'PEN',
        badge: 'Móvil',
        accountLabel: 'Número de celular asociado a Yape',
        accountPlaceholder: 'Ej. 987654321',
        accountType: 'phone',
        requiresHolder: false,
      },
      {
        key: 'interbank',
        label: 'Interbank',
        currency: 'PEN',
        badge: 'Soles / USD',
        accountLabel: 'Número de cuenta Interbank',
        accountPlaceholder: 'Ej. 200-XXXXXXXXXX',
        accountType: 'numeric',
        supportsCci: true,
        requiresHolder: false,
      },
      {
        key: 'bbva_pe',
        label: 'BBVA Perú',
        currency: 'PEN',
        badge: 'Soles / USD',
        accountLabel: 'Número de cuenta BBVA',
        accountPlaceholder: 'Ej. 0011-XXXX-XXXXXXXXXX',
        accountType: 'numeric',
        supportsCci: true,
        requiresHolder: false,
      },
      {
        key: 'scotiabank_pe',
        label: 'Scotiabank Perú',
        currency: 'PEN',
        badge: 'Soles / USD',
        accountLabel: 'Número de cuenta Scotiabank',
        accountPlaceholder: 'Ej. 000-XXXXXXX',
        accountType: 'numeric',
        supportsCci: true,
        requiresHolder: false,
      },
      {
        key: 'plin',
        label: 'PLIN',
        currency: 'PEN',
        badge: 'Móvil',
        accountLabel: 'Número de celular asociado a Plin',
        accountPlaceholder: 'Ej. 987654321',
        accountType: 'phone',
        requiresHolder: false,
      },
      {
        key: 'banco_nacion',
        label: 'Banco de la Nación',
        currency: 'PEN',
        badge: 'BN Perú',
        accountLabel: 'Número de cuenta Banco de la Nación',
        accountPlaceholder: 'Ej. 04-XXX-XXXXXX',
        accountType: 'numeric',
        supportsCci: true,
        requiresHolder: false,
      },
      {
        key: 'falabella_pe',
        label: 'Banco Falabella',
        currency: 'PEN',
        badge: 'Soles',
        accountLabel: 'Número de cuenta Falabella',
        accountPlaceholder: 'Ej. 1234567890',
        accountType: 'numeric',
        requiresHolder: false,
      },
    ],
  },
  {
    id: 'bolivia',
    name: 'Bolivia',
    defaultCurrency: 'BOB',
    currencies: ['BOB', 'USD'],
    methods: [
      {
        key: 'bnb',
        label: 'Banco Nacional de Bolivia (BNB)',
        currency: 'BOB',
        badge: 'Bs. / USD',
        accountLabel: 'Número de cuenta BNB',
        accountPlaceholder: 'Ej. 1000XXXXXX',
        accountType: 'numeric',
        requiresHolder: true,
      },
      {
        key: 'banco_union',
        label: 'Banco Unión',
        currency: 'BOB',
        badge: 'Bs.',
        accountLabel: 'Número de cuenta Banco Unión',
        accountPlaceholder: 'Ej. 100000XXXXXX',
        accountType: 'numeric',
        requiresHolder: true,
      },
      {
        key: 'banco_mercantil',
        label: 'Banco Mercantil Santa Cruz',
        currency: 'BOB',
        badge: 'Bs. / USD',
        accountLabel: 'Número de cuenta Mercantil Santa Cruz',
        accountPlaceholder: 'Ej. 4010XXXXXX',
        accountType: 'numeric',
        requiresHolder: true,
      },
      {
        key: 'banco_bisa',
        label: 'Banco BISA',
        currency: 'BOB',
        badge: 'Bs.',
        accountLabel: 'Número de cuenta Banco BISA',
        accountPlaceholder: 'Ej. 2000XXXXXX',
        accountType: 'numeric',
        requiresHolder: true,
      },
      {
        key: 'banco_fie',
        label: 'Banco FIE',
        currency: 'BOB',
        badge: 'Bs.',
        accountLabel: 'Número de cuenta FIE',
        accountPlaceholder: 'Ej. 3000XXXXXX',
        accountType: 'numeric',
        requiresHolder: true,
      },
      {
        key: 'tigo_money_bo',
        label: 'Tigo Money',
        currency: 'BOB',
        badge: 'Móvil',
        accountLabel: 'Número de celular Tigo Money',
        accountPlaceholder: 'Ej. 7XXXXXXX',
        accountType: 'phone',
        requiresHolder: true,
      },
      {
        key: 'qr_simple_bo',
        label: 'QR Simple / Transferencia Interbancaria',
        currency: 'BOB',
        badge: 'Interbancario',
        accountLabel: 'Número de cuenta o Celular',
        accountPlaceholder: 'Indique su número de cuenta para abono',
        accountType: 'text',
        requiresHolder: true,
      },
    ],
  },
  {
    id: 'colombia',
    name: 'Colombia',
    defaultCurrency: 'COP',
    methods: [
      {
        key: 'bancolombia',
        label: 'Bancolombia',
        currency: 'COP',
        badge: 'Ahorros/Cte',
        accountLabel: 'Número de cuenta Bancolombia',
        accountPlaceholder: 'Ej. 123-456789-01',
        accountType: 'numeric',
        requiresHolder: true,
      },
      {
        key: 'nequi',
        label: 'Nequi',
        currency: 'COP',
        badge: 'Móvil',
        accountLabel: 'Número de celular Nequi (10 dígitos)',
        accountPlaceholder: 'Ej. 3001234567',
        accountType: 'phone',
        requiresHolder: true,
      },
      {
        key: 'daviplata',
        label: 'Daviplata',
        currency: 'COP',
        badge: 'Móvil',
        accountLabel: 'Número de celular Daviplata',
        accountPlaceholder: 'Ej. 3101234567',
        accountType: 'phone',
        requiresHolder: true,
      },
      {
        key: 'davivienda',
        label: 'Banco Davivienda',
        currency: 'COP',
        badge: 'Bancario',
        accountLabel: 'Número de cuenta Davivienda',
        accountPlaceholder: 'Ej. 0081XXXXXXXX',
        accountType: 'numeric',
        requiresHolder: true,
      },
      {
        key: 'bbva_co',
        label: 'BBVA Colombia',
        currency: 'COP',
        badge: 'Bancario',
        accountLabel: 'Número de cuenta BBVA Colombia',
        accountPlaceholder: 'Ej. 0013XXXXXXXX',
        accountType: 'numeric',
        requiresHolder: true,
      },
      {
        key: 'banco_bogota',
        label: 'Banco de Bogotá',
        currency: 'COP',
        badge: 'Bancario',
        accountLabel: 'Número de cuenta Banco de Bogotá',
        accountPlaceholder: 'Ej. 012345678',
        accountType: 'numeric',
        requiresHolder: true,
      },
    ],
  },
  {
    id: 'mexico',
    name: 'México',
    defaultCurrency: 'MXN',
    methods: [
      {
        key: 'spei_clabe',
        label: 'Transferencia SPEI (CLABE)',
        currency: 'MXN',
        badge: '18 dígitos',
        accountLabel: 'CLABE Interbancaria (18 dígitos)',
        accountPlaceholder: 'Ej. 012180001234567890',
        accountType: 'clabe',
        requiresBankName: true,
        requiresHolder: true,
      },
      {
        key: 'bbva_mx',
        label: 'BBVA México',
        currency: 'MXN',
        badge: 'Cuenta/Tarjeta',
        accountLabel: 'Número de cuenta o CLABE',
        accountPlaceholder: 'Ej. 0123456789 o CLABE',
        accountType: 'numeric',
        requiresHolder: true,
      },
      {
        key: 'santander_mx',
        label: 'Santander México',
        currency: 'MXN',
        badge: 'Bancario',
        accountLabel: 'Número de cuenta o CLABE Santander',
        accountPlaceholder: 'Ej. 6051XXXXXXXX',
        accountType: 'numeric',
        requiresHolder: true,
      },
      {
        key: 'banorte',
        label: 'Banorte',
        currency: 'MXN',
        badge: 'Bancario',
        accountLabel: 'Número de cuenta o CLABE Banorte',
        accountPlaceholder: 'Ej. 0123456789',
        accountType: 'numeric',
        requiresHolder: true,
      },
      {
        key: 'mercado_pago_mx',
        label: 'Mercado Pago México',
        currency: 'MXN',
        badge: 'Digital',
        accountLabel: 'CLABE de Mercado Pago (18 dígitos) o Teléfono',
        accountPlaceholder: 'Ej. 722XXXXXXXXXXXXXXX',
        accountType: 'text',
        requiresHolder: true,
      },
    ],
  },
  {
    id: 'chile',
    name: 'Chile',
    defaultCurrency: 'CLP',
    methods: [
      {
        key: 'cuenta_rut',
        label: 'BancoEstado (CuentaRUT)',
        currency: 'CLP',
        badge: 'RUT',
        accountLabel: 'RUT del titular (sin puntos y con guión)',
        accountPlaceholder: 'Ej. 12345678-9',
        accountType: 'text',
        requiresHolder: true,
      },
      {
        key: 'santander_cl',
        label: 'Santander Chile',
        currency: 'CLP',
        badge: 'Bancario',
        accountLabel: 'Número de cuenta corriente o vista',
        accountPlaceholder: 'Ej. 0-000-XXXXXXXX',
        accountType: 'text',
        requiresHolder: true,
      },
      {
        key: 'banco_chile',
        label: 'Banco de Chile / Edwards',
        currency: 'CLP',
        badge: 'Bancario',
        accountLabel: 'Número de cuenta corriente',
        accountPlaceholder: 'Ej. 00-XXX-XXXXX-XX',
        accountType: 'text',
        requiresHolder: true,
      },
      {
        key: 'bci',
        label: 'BCI',
        currency: 'CLP',
        badge: 'Bancario',
        accountLabel: 'Número de cuenta BCI',
        accountPlaceholder: 'Ej. 12345678',
        accountType: 'text',
        requiresHolder: true,
      },
      {
        key: 'falabella_cl',
        label: 'Banco Falabella Chile',
        currency: 'CLP',
        badge: 'Bancario',
        accountLabel: 'Número de cuenta',
        accountPlaceholder: 'Ej. 1234567890',
        accountType: 'text',
        requiresHolder: true,
      },
    ],
  },
  {
    id: 'argentina',
    name: 'Argentina',
    defaultCurrency: 'ARS',
    currencies: ['ARS', 'USD'],
    methods: [
      {
        key: 'cbu_cvu',
        label: 'Transferencia Bancaria (CBU / CVU / Alias)',
        currency: 'ARS',
        badge: 'CBU/CVU/Alias',
        accountLabel: 'CBU / CVU (22 dígitos) o Alias bancario',
        accountPlaceholder: 'Ej. 0110599540000001234567 o alias.banco.ar',
        accountType: 'text',
        requiresHolder: true,
        holderLabel: 'Nombre del titular y CUIL/CUIT',
      },
      {
        key: 'mercado_pago_ar',
        label: 'Mercado Pago Argentina',
        currency: 'ARS',
        badge: 'CVU/Alias',
        accountLabel: 'CVU o Alias de Mercado Pago',
        accountPlaceholder: 'Ej. 00000031000XXXXXXXXXXX o alias.mp',
        accountType: 'text',
        requiresHolder: true,
      },
      {
        key: 'brubank',
        label: 'Brubank',
        currency: 'ARS',
        badge: 'CBU/Alias',
        accountLabel: 'CBU o Alias de Brubank',
        accountPlaceholder: 'Ej. brubank.alias',
        accountType: 'text',
        requiresHolder: true,
      },
    ],
  },
  {
    id: 'ecuador',
    name: 'Ecuador',
    defaultCurrency: 'USD',
    methods: [
      {
        key: 'banco_pichincha',
        label: 'Banco Pichincha',
        currency: 'USD',
        badge: 'USD',
        accountLabel: 'Número de cuenta de ahorros o corriente',
        accountPlaceholder: 'Ej. 2100XXXXXX',
        accountType: 'numeric',
        requiresHolder: true,
      },
      {
        key: 'banco_guayaquil',
        label: 'Banco Guayaquil',
        currency: 'USD',
        badge: 'USD',
        accountLabel: 'Número de cuenta',
        accountPlaceholder: 'Ej. 0012XXXXXX',
        accountType: 'numeric',
        requiresHolder: true,
      },
      {
        key: 'produbanco',
        label: 'Produbanco',
        currency: 'USD',
        badge: 'USD',
        accountLabel: 'Número de cuenta',
        accountPlaceholder: 'Ej. 1200XXXXXX',
        accountType: 'numeric',
        requiresHolder: true,
      },
    ],
  },
  {
    id: 'norteamerica',
    name: 'Estados Unidos / Canadá',
    defaultCurrency: 'USD',
    currencies: ['USD', 'CAD'],
    methods: [
      {
        key: 'zelle_us',
        label: 'Zelle (EE.UU.)',
        currency: 'USD',
        badge: 'Directo USD',
        accountLabel: 'Correo electrónico o número móvil en EE.UU.',
        accountPlaceholder: 'name@email.com o (555) 000-0000',
        accountType: 'text',
        requiresHolder: true,
        holderLabel: 'Nombre del titular de la cuenta en Zelle',
      },
      {
        key: 'ach_wire_us',
        label: 'Depósito Directo ACH / Wire (EE.UU.)',
        currency: 'USD',
        badge: 'ACH / Routing',
        accountLabel: 'Número de cuenta bancaria',
        accountPlaceholder: 'Ej. 123456789',
        accountType: 'numeric',
        requiresBankName: true,
        requiresRouting: true,
        requiresHolder: true,
      },
      {
        key: 'interac_ca',
        label: 'Interac e-Transfer (Canadá)',
        currency: 'CAD',
        badge: 'CAD Interac',
        accountLabel: 'Correo electrónico registrado en Interac',
        accountPlaceholder: 'ejemplo@correo.ca',
        accountType: 'email',
        requiresHolder: true,
      },
    ],
  },
  {
    id: 'otros_latam',
    name: 'Otros Sudamérica',
    defaultCurrency: 'USD',
    methods: [
      {
        key: 'pix_br',
        label: 'Pix (Brasil)',
        currency: 'BRL',
        badge: 'Chave Pix',
        accountLabel: 'Chave Pix (CPF, Email, Celular o Clave Aleatoria)',
        accountPlaceholder: 'Ej. 123.456.789-00 o email@dominio.com',
        accountType: 'text',
        requiresHolder: true,
      },
      {
        key: 'pago_movil_ve',
        label: 'Pago Móvil (Venezuela)',
        currency: 'USD',
        badge: 'Móvil',
        accountLabel: 'Teléfono, Cédula (V/E) y Banco destino',
        accountPlaceholder: 'Ej. 0414-1234567, V-12345678, Banesco',
        accountType: 'text',
        requiresHolder: true,
      },
      {
        key: 'banco_uruguay',
        label: 'Banco Local (Uruguay / Paraguay / Otro)',
        currency: 'USD',
        badge: 'Local / USD',
        accountLabel: 'Número de cuenta bancaria',
        accountPlaceholder: 'Número de cuenta completo',
        accountType: 'text',
        requiresBankName: true,
        requiresHolder: true,
      },
    ],
  },
  {
    id: 'otro_general',
    name: 'Otro Método',
    defaultCurrency: 'USD',
    methods: [
      {
        key: 'otro',
        label: 'Otro método o entidad personalizada',
        currency: 'USD',
        badge: 'Personalizado',
        accountLabel: 'Datos de abono / Número de cuenta / Identificador',
        accountPlaceholder: 'Indique su número de cuenta, correo o identificador de cobro',
        accountType: 'text',
        requiresCustomName: true,
        requiresHolder: true,
      },
    ],
  },
];

export function findMethodConfig(methodKey) {
  if (!methodKey) return null;
  for (const region of PAYMENT_REGIONS) {
    const found = region.methods.find((m) => m.key === methodKey);
    if (found) {
      return { ...found, regionId: region.id, regionName: region.name };
    }
  }
  return null;
}

export function formatPaymentSummary(formData) {
  const method = findMethodConfig(formData.metodoPago);
  const currency = formData.monedaPago || method?.currency || 'USD';
  const methodName =
    formData.metodoPago === 'otro'
      ? formData.metodoPagoOtro || 'Otro método'
      : method?.label || formData.metodoPago?.toUpperCase() || 'Sin método';

  return `${methodName} (${currency})`;
}
